name: Build and Publish Docker Image

on:
  pull_request:
    paths:
    - .github/workflows/docker-build.yml
    - build.sh
    - Dockerfile

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build-and-publish:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Run build script
      run: |
        bash build.sh

    

    
